project:
  type: website

website:
  description: "Publications and notes"
  site-url: https://ticlext.top # you must change this appropriately for RSS feeds to work properly
  title: "Ticlext Altihaf"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ticlext-Altihaf
      - icon: linkedin
        href: https://www.linkedin.com/in/yusuf-sekhan-althaf/


author:
  name: "Y Sekhan Althaf"
  url: "/about.html"
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



