project:
  type: website

website:
  description: "Publications and notes"
  site-url: https://ticlext.top # you must change this appropriately for RSS feeds to work properly
  title: "Ticlext Altihaf"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



